## 練習時間
假設我們資料中類別的數量並不均衡，在評估準確率時可能會有所偏頗，試著切分出 y_test 中，0 類別與 1 類別的數量是一樣的 (亦即 y_test 的類別是均衡的)

In [1]:
import numpy as np
X = np.arange(1000).reshape(200, 5)
y = np.zeros(200)
y[:40] = 1

In [2]:
y

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

可以看見 y 類別中，有 160 個 類別 0，40 個 類別 1 ，請試著使用 train_test_split 函數，切分出 y_test 中能各有 10 筆類別 0 與 10 筆類別 1 。(HINT: 參考函數中的 test_size，可針對不同類別各自作切分後再合併)

In [4]:
from sklearn.model_selection import train_test_split, KFold
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [5]:
X_train

array([[210, 211, 212, 213, 214],
       [945, 946, 947, 948, 949],
       [450, 451, 452, 453, 454],
       [680, 681, 682, 683, 684],
       [255, 256, 257, 258, 259],
       [635, 636, 637, 638, 639],
       [810, 811, 812, 813, 814],
       [205, 206, 207, 208, 209],
       [590, 591, 592, 593, 594],
       [565, 566, 567, 568, 569],
       [130, 131, 132, 133, 134],
       [695, 696, 697, 698, 699],
       [500, 501, 502, 503, 504],
       [555, 556, 557, 558, 559],
       [ 10,  11,  12,  13,  14],
       [385, 386, 387, 388, 389],
       [230, 231, 232, 233, 234],
       [935, 936, 937, 938, 939],
       [955, 956, 957, 958, 959],
       [425, 426, 427, 428, 429],
       [805, 806, 807, 808, 809],
       [180, 181, 182, 183, 184],
       [950, 951, 952, 953, 954],
       [305, 306, 307, 308, 309],
       [110, 111, 112, 113, 114],
       [705, 706, 707, 708, 709],
       [505, 506, 507, 508, 509],
       [165, 166, 167, 168, 169],
       [ 55,  56,  57,  58,  59],
       [970, 9

In [6]:
X_test

array([[475, 476, 477, 478, 479],
       [ 75,  76,  77,  78,  79],
       [150, 151, 152, 153, 154],
       [790, 791, 792, 793, 794],
       [640, 641, 642, 643, 644],
       [575, 576, 577, 578, 579],
       [345, 346, 347, 348, 349],
       [850, 851, 852, 853, 854],
       [870, 871, 872, 873, 874],
       [225, 226, 227, 228, 229],
       [330, 331, 332, 333, 334],
       [910, 911, 912, 913, 914],
       [825, 826, 827, 828, 829],
       [390, 391, 392, 393, 394],
       [930, 931, 932, 933, 934],
       [885, 886, 887, 888, 889],
       [280, 281, 282, 283, 284],
       [760, 761, 762, 763, 764],
       [410, 411, 412, 413, 414],
       [340, 341, 342, 343, 344],
       [620, 621, 622, 623, 624],
       [ 80,  81,  82,  83,  84],
       [740, 741, 742, 743, 744],
       [465, 466, 467, 468, 469],
       [325, 326, 327, 328, 329],
       [300, 301, 302, 303, 304],
       [420, 421, 422, 423, 424],
       [335, 336, 337, 338, 339],
       [625, 626, 627, 628, 629],
       [660, 6

In [7]:
y_train

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 1., 1., 0., 0., 1., 1., 0.,
       1., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
       0., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0.])

In [8]:
y_test

array([0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 1., 1., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0.])

In [9]:
#可以看見 y 類別中，有 160 個 類別 0，40 個 類別 1 ，請試著使用 train_test_split 函數，切分出 y_test 中能各有 10 筆類別 0 與 10 筆類別 1 。(HINT: 參考函數中的 test_size，可針對不同類別各自作切分後再合併)
y_1_index, y_0_index = np.where(y==1)[0], np.where(y==0)[0] # 選出 y 等於 1 的 index 與 y 等於 0 的 index

In [10]:
y_1_index

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [11]:
train_data_y1, test_data_y1, train_label_y1, test_label_y1 = train_test_split(X[y_1_index], y[y_1_index], test_size=10)
train_data_y0, test_data_y0, train_label_y0, test_label_y0 = train_test_split(X[y_0_index], y[y_0_index], test_size=10)

In [12]:
# 將 (X, y) 中 y 等於 1 的部分取出作 train/test split，指定 test_size=10； y 等於 0 的部分也做一樣的操作
train_data_y1, test_data_y1, train_label_y1, test_label_y1 = train_test_split(X[y_1_index], y[y_1_index], test_size=10)
train_data_y0, test_data_y0, train_label_y0, test_label_y0 = train_test_split(X[y_0_index], y[y_0_index], test_size=10)

In [13]:
#再將分好的 data 與 label 合併起來，變回我們熟悉的 x_train, x_test, y_train, y_test
x_train, y_train = np.concatenate([train_data_y1, train_data_y0]), np.concatenate([train_label_y1, train_label_y0])
x_test, y_test = np.concatenate([test_data_y1, test_data_y0]), np.concatenate([test_label_y1, test_label_y0])

In [14]:
y_test

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])